return {
  {type = meta,value = 'Hieracosphinx (J-6)'},
  {type = item,id = 2925},
  {type = meta,value = 'Jaguarundi (G-6)'},
  {type = item,id = 2924},
  {type = meta,value = 'Tefenet (G-6)'},
  {type = item,id = 2950},
  {type = meta,value = 'Muscaliet (J-6)'},
  {type = key_item,id = 1474},
  {type = meta,value = 'Cluckatrice (H-8)'},
  {type = item,id = 2923},
  {type = meta,value = 'Canyon Eft (K-10)'},
  {type = item,id = 2922},
  {type = meta,value = 'Abas (K-10)'},
  {type = item,id = 2949},
  {type = meta,value = 'Alectryon (H-8)'},
  {type = key_item,id = 1472},
  {type = meta,value = 'Adze (G-5)'},
  {type = key_item,id = 1475},
  {type = meta,value = 'Minhocao (I-6)'},
  {type = key_item,id = 1473},
  {type = meta,value = 'Glavoid (I-5)'},
  {type = count_items,id = 2927, amount = 50}
}